Fix missing rsync error during installation
I got this error:

```shell
10:38 $ brew install adobe-marketing-cloud/brews/repo
==> Installing repo from adobe-marketing-cloud/homebrew-brews
Error: No available formula with the name "rsync" (dependency of adobe-marketing-cloud/brews/repo)
==> Searching for similarly named formulae...
These similarly named formulae were found:
grsync                                                                                                                    librsync                                                                                                                  vdirsyncer
To install one of them, run (for example):
  brew install grsync
==> Searching taps...
These formulae were found in taps:
homebrew/dupes/rsync                                                                       Caskroom/cask/arrsync                                                                      Caskroom/cask/comicbookloversync                                                           Caskroom/cask/supersync
To install one of them, run (for example):
  brew install homebrew/dupes/rsync
```